remote_theme: konstantin-morenko/just-the-docs

title: Коллекция
description: Персональная коллекция проектов и ссылок Константина Моренко

aux_links:
  "Константин Моренко":
    - "https://konstantin-morenko.ru"

search_enabled: true
ycnumber: 69954367