remote_theme: pmarsceill/just-the-docs

title: Все проекты Константин Моренко
description: Коллекция всех проектов Константина Моренко

aux_links:
  "Константин Моренко":
    - "https://konstantin-morenko.ru"
